# Generated by Django 3.1.7 on 2021-03-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns_field', models.CharField(blank=True, choices=[('1', 'One')], max_length=100)),
                ('vizualization_field', models.CharField(blank=True, choices=[('line', 'Line'), ('bar', 'Bar'), ('pie', 'Pie'), ('doughnut', 'Doughnut'), ('radar', 'Radar'), ('polar', 'Polar Area'), ('bubble', 'Bubble'), ('scatter', 'Scatter ')], max_length=100)),
            ],
        ),
    ]
